### ISSUE TITLE
Batch manager error trying to move virtual photos

### ISSUE THREAD

**Issue by jradwan** [jradwan/Piwigo-physical_photo_move#10]
From eliz82 on the Piwigo forums ([post](http://piwigo.org/forum/viewtopic.php?pid=169733#p169733)):

In some specific conditions Batch Manager can give some error

You know you are able to add (virtual) photos to physical albums from admin interface? For example you have some physical albums, go to "admin->photos->add" and you can select a physical album -> upload photos . Now the photos are in piwigo/upload/ folder (so they are not physical). But if you go to client font end they are showed in the same album as the physical photos. So you can combine the virtual photos and physical ones in a physical album.

Now if you go to Admin->Batch Manager->Add filter->Predefined filter->With no virtual albums

Well ... this also show both virtual and physical photos. Seems to me there is no way to filter only physical photos from a physical album.

If you select a virtual one by mistake and you try to move it => error

```
Warning: [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

SELECT *
  FROM piwigo_categories
  WHERE id = 
; in /www/local/piwigo/include/dblayer/functions_mysqli.inc.php on line 845

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /usr/local/piwigo-beta/include/dblayer/functions_mysqli.inc.php:226 Stack trace: #0 /usr/local/piwigo-beta/include/functions_category.inc.php(176): pwg_db_fetch_assoc(false) #1 /usr/local/piwigo-beta/plugins/physical_photo_move/include/functions.inc.php(102): get_cat_info(NULL) #2 /usr/local/piwigo-beta/plugins/physical_photo_move/include/functions.inc.php(79): ppm_move_photo('37', '431', true) #3 /usr/local/piwigo-beta/plugins/physical_photo_move/batch_global.php(77): ppm_move_item('37', '431', true, 'photo') #4 /usr/local/piwigo-beta/include/functions_plugins.inc.php(279): ppm_batch_global_submit('ppm', Array) #5 /usr/local/piwigo-beta/admin/batch_manager_global.php(425): trigger_notify('element_set_glo...', 'ppm', Array) #6 /usr/local/piwigo-beta/admin/batch_manager.php(795): include('/usr/local/piwi...') #7 /usr/local/piwigo-beta/admin.php(311): include('/usr/local/piwi...') #8 {main} thrown in /usr/local/piwigo-beta/include/dblayer/functions_mysqli.inc.php on line 226
```

**Comment by jradwan** [comment]
Fixed in 2.02.
